#!/bin/bash
#
# reads final coordinates from pw.x output and
# writes to screen in crystal coordinates and 
# in angstrom for comparison
awk 'BEGIN{
        parse=0
        i=0}
 {if($1=="celldm(1)="){
        a=$2*0.5292
        b=a*$4
        c=a*$6
        next}
  if($1=="Begin" && $2=="final") {
        parse=1
        next}
  if($1=="End" && $2=="final" && $3=="coordinates")
        exit
  if(parse==1){
        if($2~/(angstrom)/){
                flg=0
        }
        else if($2~/(crystal)/){
                flg=1;
        }
        else if($4!=""){
  		        if( i % 2 == 1 )
	                printf "\033[38;5;181m"
	            i=i+1
			    if(flg==0){x=$2/a;y=$3/b;z=$4/c;x1=$2;y1=$3;z1=$4}
                else{x=$2;y=$3;z=$4;x1=a*$2;y1=b*$3;z1=c*$4}
	            printf "%-3d %-5s %12.8f %12.8f %12.8f   | %10.6f %10.6f %10.6f\033[0m\n", i, $1, x, y, z, x1, y1, z1
        }
}}' output.txt
