#!/usr/bin/env bash
~/software/plot/main.rb "$@"
# input=$1
# # if [[ $2 != "" ]]; then
# #   plotfile="_"$1
# #   cat /dev/null > $plotfile
# # fi

# while read -r line;do 
#   set -- $line
#   if  [[ "$1" = "##" ]];then
#     if  [[ "$2" == \[* ]];then
#       i=3
#       tmp=${2#\[*}
#       while [[ "${!i}" != *\] ]]; do
#         tmp="${tmp[@]} ${!i}"
#         let i++
#       done
#       tmp="$tmp ${!i%*\]}"
#       let i++
#       eval arr=( $tmp )
#       line=`echo $line|cut -d " " -f $i-`
#       index=1
#       loop=0
#       for i in "${arr[@]}";do 
#         tmp=$line
#         tmp=${tmp//\#i/$index}
#         tmp=${tmp//\#l/$loop}
#         tmp=${tmp//\#1/${arr[$loop]}}
#         let index++
#         let loop++
#         echo "$tmp" 
#       done
#     else
#       line=`echo $line|cut -d " " -f 3-`
#       index=1
#       loop=0
#       while read -r l; do 
#         tmp=$line
#         tmp=${tmp//\#i/$index}
#         tmp=${tmp//\#l/$loop}
#         set -- $l   
#         for (( i = 1; i < $(($#+1)); i++ )); do
#           tmp=${tmp//\#$i/${!i}}
#         done
#         echo "$tmp"
#         let index++
#         let loop++
#       done < $2
#     fi
#   else
#     echo "$line"
#   fi
# done < $input 
