#!/usr/bin/env bash
filename='dos'
outdir='./'
queue="cfn_short"
node="gen03"
time=10

while [[ $# > 0 ]]; do
  if [[ "$1" == *./* ]]; then
    outdir="$1"
    shift
  elif [[ $1 = -o ]]; then
    shift
    filename=$1
    plots[0]=$filename.dat
    shift 
  elif [[ $1 = -t ]]; then
    shift
    time=$1
    shift
  elif [[ $1 = -g ]]; then
    queue="cfn_gen04"
    node="gen04"
    shift
  fi
done

echo -e "&INPUTPP\n  outdir = '$outdir'\n  DeltaE= 0.01, \n fildos = '$filename.dat'\n/" > $filename.in

cat > $filename.job << EOF
#!/bin/bash
#PBS -l nodes=1:ppn=1:$node,walltime=00:$time:00
#PBS -q $queue
#PBS -m ae
#PBS -M sselcuk@princeton.edu
#PBS -j oe
#PBS -o /dev/null
#PBS -V
module load intel intel_mkl mvapich2/1.4-intel
kpools=1
images=1
gap=300
exec_path="\$HOME/software/espresso-4.3.2/bin/"
echo "\$USER \${PBS_JOBID%%.*} \$(date +%s) started \$(wc -l < \$PBS_NODEFILE)" >> /work/sselcuk/usage.log
cd \$PBS_O_WORKDIR
mpirun_rsh -ssh -hostfile \$PBS_NODEFILE -np 1 \${exec_path}dos.x < $filename.in > $outdir/$filename.out
echo "\$USER \${PBS_JOBID%%.*} \$(date +%s) died" >> /work/sselcuk/usage.log
rm $filename.in $filename.job 
EOF

qsub $filename.job
