#!/bin/bash
#
# creates a input file using another input file for
# options, and final coordinates from a pw.x calculation
# as the starting geometry (in angstroms).
function cin {
	filein1=${1}output.txt
	filein2=${1}input.txt
	echo -n $1 " -> "
	fileout=$2
	echo $fileout
awk '{if($1~/ATOMIC_POSITIONS/) {print "ATOMIC_POSITIONS (angstrom)";exit 1;} print $0;}' $filein2 > $fileout
awk 'BEGIN{
	parse=0
	}
 {if($1=="celldm(1)="){
	a=$2*0.5292
	b=a*$4
	c=a*$6
	next} 
  if($1=="Begin" && $2=="final") {
	parse=1
	next}
  if($1=="End" && $2=="final" && $3=="coordinates"){
	print "K_POINTS gamma"
	exit}
  if(parse==1){
	if($2~/(crystal)/){
		flg=0
	}
	else if($2~/(angstrom)/){
		flg=1;
	}
	else if($4!=""){
		if(flg==0){x=a*$2;y=b*$3;z=c*$4;}
		else{x=$2;y=$3;z=$4}
		printf "%-5s %12.8f %12.8f %12.8f",  $1, x, y, z
		if(NF==7)
			printf "  0  0  0"
		printf "\n"
	}
}}' $filein1 >> $fileout

}


if [ $# == 0 ];then
        a=$(echo `basename $(pwd)`)
	filepath="./"
	fileout=$a".txt"
        cin $filepath $fileout 
else
	if [[ ! -d "inputs" ]];then
		mkdir inputs
        fi
        while [ $# -ne 0 ];do
	        filepath=${1%/*}
                fileout="inputs/"$(echo `basename $filepath`)".txt"
		cin $filepath $fileout 
                shift
	done
fi
