#!/usr/bin/env ruby
require 'diyanet'

a = Diyanet.Namaz()

if a.oku('/home/sselcuk/.settings/.namaz')
elsif a.baglan("ABD", "PRINCETON")
  a.yaz
else
  puts "export NAMAZ=-1" 
  exit
end

if ARGV[0].nil?
  i, j = a.index
  puts "export NAMAZ=#{a[i][j].strftime('%s').to_i/60+300}"
elsif ARGV[0].to_i > 0 
  a.to_s(ARGV[0])
else
  a.to_s
end
